### ISSUE TITLE
libmaven?

### ISSUE THREAD

**Issue by pombreda** [sassoftware/mirrorball#1]
Howdy @wfscheper 
This commit 7f91038ec2cd2dfc851a6882352bafcdc4b1173b introduced a libmaven module that I cannot find anywhere. Any clues of where I could find it?
Thanks!

**Comment by pombreda** [comment]
@wfscheper Shall I assume that the for now empty pymaven will be the home for libmaven?

**Comment by wfscheper** [comment]
Yep, we're still going to through the process of getting that repo mirrored out. Not sure when it will be done, but shouldn't be too much longer. I'm hoping for early next week.

**Comment by conarysync** [comment]
sassoftware/pymaven is now mirrored out

**Comment by pombredanne** [comment]
@wfscheper thank you ++ !
